# Nueva sección

In [ ]:
import numpy as np


In [ ]:
print(np.__version__)
np.show_config()

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

In [ ]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
z=np.zeros(10)
Z[4]=1
print(Z)
print(np.std(Z))
print('la media de este array % f'%(np.mean(z)))

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
0.30000000000000004
la media de este array  0.000000


In [ ]:
zmedia=np.mean(z)
dmedia=np.std(z)
print("la media de este array es",zmedia, "su desviación estandar es",dmedia)


la media de este array es 0.0 su desviación estandar es 0.0


In [ ]:
np.arange(10,50,dtype=int)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
Z = np.linspace(2,20,7)[::-1]
Z = Z[::-1]
print(Z)

[ 2.  5.  8. 11. 14. 17. 20.]


In [ ]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
##9 - Encuentre los índices de elementos distintos de cero de `[7,5,0,0,2,1]`.

nz = np.nonzero([7,5,0,0,2,1])
print(nz)


(array([0, 1, 4, 5]),)


In [ ]:
E=[7,5,0,0,2,-1]
e=[x for x in E if x !=0]
print(e)


[7, 5, 2, -1]


In [ ]:
M = np.array(E)
print(M[np.nonzero(M)])

[ 7  5  2 -1]


In [ ]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.10139021 0.97733017 0.84529164]
  [0.40608692 0.83488654 0.56415448]
  [0.91475907 0.9815323  0.49961278]]

 [[0.00529453 0.77442941 0.40741211]
  [0.32786108 0.970219   0.99481015]
  [0.89135524 0.25464456 0.86833425]]

 [[0.52734745 0.96369421 0.96363862]
  [0.7582513  0.3036282  0.29793033]
  [0.26270362 0.17896666 0.13196774]]]


In [ ]:
##12 - Cree una matriz de 10x10 con valores aleatorios y encuentre el mínimo y el máximo.



In [ ]:
l=np.random.random((10,10))
print(l)


[[0.05016415 0.14317098 0.13700079 0.6419785  0.52061986 0.20126188
  0.14388312 0.96774327 0.98388991 0.33659229]
 [0.57923747 0.60593154 0.10825907 0.93389953 0.03851046 0.94461183
  0.18133027 0.51052435 0.64603179 0.21331983]
 [0.79980887 0.59063462 0.9578861  0.44892999 0.5559534  0.13935488
  0.85884337 0.20250762 0.84724188 0.83279965]
 [0.56209087 0.65362577 0.37239902 0.29045472 0.53045092 0.8961873
  0.97218401 0.89534946 0.0621462  0.26537536]
 [0.0840947  0.43964287 0.62295578 0.59271678 0.66530589 0.90072262
  0.6303112  0.12485729 0.95981537 0.00350946]
 [0.02945058 0.18647384 0.54638187 0.30620675 0.77155745 0.65112926
  0.21527014 0.04775565 0.82444887 0.0446654 ]
 [0.44524405 0.90384514 0.43988433 0.53624213 0.86016935 0.83373156
  0.29229122 0.67485958 0.1714855  0.60967995]
 [0.73208336 0.63835617 0.58284346 0.0450076  0.278321   0.30255149
  0.90767796 0.23215372 0.91738812 0.0458801 ]
 [0.25146454 0.57660071 0.75690328 0.9273233  0.56205884 0.01350314
  0.14373429 

In [ ]:
l=np.random.random((10,10))
print("El Maximo de la matriz es {}".format(l.max()))

El Maximo de la matriz es 0.9974514024325645


In [ ]:
print("El Mínimo de la matriz es {}".format(l.min()))

El Mínimo de la matriz es 0.002028925298576678


In [ ]:
#Generad una matriz llamada mat_al_2_8 que genere números aleatorios entre el 2 y el 8

In [ ]:

mat_al_2_8 = 6*np.random.random((3,3))
print(mat_al_2_8 )

[[4.94745726 0.52098719 3.69225858]
 [3.84147875 2.72324391 5.90440897]
 [0.75000119 2.58420666 0.15522808]]


In [ ]:
#Genera una función matriz llamada matriznormal a la que podamos pedirle una matriz cuadrada (con dimensión a especificar)
 #y cuyos datos sigan una distribución normal (con media y desviación típica a especificar).
 #Asignad el valor "1" por defecto a la dimensión

In [ ]:
def matriz_normal(media, desviacion, dimension = 1):
  numero_aleatorio = desviacion*np.random.randn(dimension**2) + media
 
  return numero_aleatorio.reshape(dimension,dimension)

In [ ]:
print(matriz_normal)(5,2,3)

<function matriz_normal at 0x7ff78e39ff80>


TypeError: ignored

In [ ]:
##13 - Cree un vector aleatorio de tamaño 50 y encuentre el valor medio.

np.random.random(50).mean()


0.5405721790240127

In [ ]:
##14 - Cree una matriz de 6x6 con valores 1,2,3,4,5 justo debajo de la diagonal.


Z = np.diag(1+np.arange(5),k=-1)
print(Z)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


In [ ]:
##15 - Considere una matriz de formas (4,5,6), ¿cuál es el índice (x,y,z) del elemento número 57?


print(np.unravel_index(56,(4,5,6)))

(1, 4, 2)


In [ ]:
##16 - Normalice una matriz aleatoria de 10x10.

`pista: (x - mean) / std`

SyntaxError: ignored

In [ ]:
Z = np.random.random((10,10))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-1.02431007  1.08929475 -0.90214983  0.02949153  0.78047759  1.66106541
   0.02589478  0.17406416 -1.11142396 -0.74927529]
 [-0.91055343  1.73898712 -0.19637678  1.52613629 -0.32344412  0.99719644
   0.19670068 -1.59169528 -0.91252482 -0.65235448]
 [-0.55598962 -1.11435498  0.0021711   0.31011797  0.85522762  0.42958393
   0.52482499  0.68410605 -1.17658507 -0.23972764]
 [-1.29754606  1.87280068  1.40992311  0.59384998 -1.61331258 -1.2247933
   1.20336377 -0.10735293  0.65551377  1.2044159 ]
 [-1.3525989  -0.43824244  1.17393598 -0.02021464 -1.07034813 -0.16598574
   1.5972735  -0.19323463 -0.06992283  0.0739573 ]
 [-0.4569646  -0.37985725 -0.4877858  -1.39141869 -0.54085762  1.46007845
   0.88428706  1.07908228 -1.54496765  1.13205781]
 [ 1.42395678 -1.37259759  0.07481436 -1.40957067 -0.70121492 -0.70957346
   0.06283048  1.06521594 -0.79367707 -1.73203711]
 [-0.63797429 -1.7490048   1.51899107  1.323801    1.20138233 -1.0439165
   1.46604116  1.90928097  0.96840953  0.17570336]
 [

In [ ]:
##17 - Multiplique una matriz de 3x2 por una matriz de 2x5.

In [ ]:
Z = np.dot(np.ones((3,2)), np.ones((2,5)))
print(Z)

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [ ]:
##18 - ¿Cómo encuentra valores comunes entre dos matrices?

`pista: np.intersect1d`


SyntaxError: ignored

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[2 5 8 9]


In [ ]:
##19 - ¿Cómo obtener las fechas de ayer, hoy y mañana?

`pista: np.datetime64, np.timedelta64`


SyntaxError: ignored

In [ ]:
ayer    = np.datetime64('today') - np.timedelta64(1)
hoy     = np.datetime64('today')
mañana  = np.datetime64('today') + np.timedelta64(1)


In [ ]:
##20 - ¿Cómo obtener todas las fechas correspondientes al mes de septiembre de 2020?

`pista: np.arange(dtype=datetime64['D'])`

SyntaxError: ignored

In [ ]:
Z = np.arange('2020-09', '2020-10', dtype='datetime64[D]')
print(Z)

['2020-09-01' '2020-09-02' '2020-09-03' '2020-09-04' '2020-09-05'
 '2020-09-06' '2020-09-07' '2020-09-08' '2020-09-09' '2020-09-10'
 '2020-09-11' '2020-09-12' '2020-09-13' '2020-09-14' '2020-09-15'
 '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19' '2020-09-20'
 '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24' '2020-09-25'
 '2020-09-26' '2020-09-27' '2020-09-28' '2020-09-29' '2020-09-30']


##21 - Extraiga la parte entera de una matriz aleatoria de números positivos usando 4 métodos diferentes.

`pista: %, np.floor, astype, np.trunc`

In [ ]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[5. 8. 3. 4. 2. 1. 0. 7. 5. 5.]
[5. 8. 3. 4. 2. 1. 0. 7. 5. 5.]
[5. 8. 3. 4. 2. 1. 0. 7. 5. 5.]
[5 8 3 4 2 1 0 7 5 5]
[5. 8. 3. 4. 2. 1. 0. 7. 5. 5.]


##22 - Cree una matriz de 10x10 con valores de fila que van de 0 a 9.

`pista: np.arange`

In [ ]:
Z = np.zeros((10,10))
Z += np.arange(10)
print(Z)


[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]


##24 - Cree un vector aleatorio de tamaño 25 y ordénelo.

`pista: sort`

In [ ]:
Z = np.random.random(25)
Z.sort()
print(Z)
print(np.sort(Z))

[0.00505128 0.03125989 0.06225026 0.08105917 0.12354682 0.14223891
 0.1765714  0.19554227 0.3269083  0.41478069 0.46939904 0.47247657
 0.47625158 0.52165688 0.63671883 0.63875047 0.64232924 0.69947731
 0.76403372 0.80346784 0.86566874 0.87344738 0.91567838 0.97531444
 0.98103845]
[0.00505128 0.03125989 0.06225026 0.08105917 0.12354682 0.14223891
 0.1765714  0.19554227 0.3269083  0.41478069 0.46939904 0.47247657
 0.47625158 0.52165688 0.63671883 0.63875047 0.64232924 0.69947731
 0.76403372 0.80346784 0.86566874 0.87344738 0.91567838 0.97531444
 0.98103845]
