
#NUMPY PART ADVANCED


In [2]:
#1 - Importa el paquete con el nombre "np".
import numpy as np
#2 - Imprime la versión instalada.
print(np.__version__)

1.21.6


In [3]:
print(np.show_config())

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

In [4]:
#3 - Crea un vector de nulos de tamaño 10.
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [24]:
#4 - Encontrar el tamaño en memoria de un array.
matrix = np.zeros((5,5))
print("El tamaño \n de este array es " + str(matrix.size * matrix.itemsize) + " bytes")

El tamaño 
 de este array es 200 bytes


In [17]:
M = np.zeros(10)
M[4] = 1
print(np.mean(M))
print(M)

0.1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [16]:
#6 - Cree un vector con valores que van de 10 a 49.
V = np.arange(10,50)
print(V)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [40]:
#Generad un vector con 7 elementos equidistantes entre el 2 y el 16. Dadle la vuelta a este vector
G = np.arange(2,17,2)
W = np.linspace(2,14,7)[::-1] #np.linspace nos da espacios equidistantes (primer numero, segundo numero, separaciones)
print(W)


[14. 12. 10.  8.  6.  4.  2.]


In [23]:
#7 - Invierta un vector (el primer elemento se convierte en el último).
RV = V[::-1]
RRV = np.flipud(V)
print(RRV)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [27]:
#8 - Cree una matriz de 3x3 con valores que van de 0 a 8.
N = np.arange(0,9).reshape(3,3)
print(N)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [58]:
#9 - Encuentre los índices de elementos distintos de cero de [7,5,0,0,2,1].
E = np.array([7,5,0,0,2,1])
I = [x for x in enumerate(E)]
print(I)

[(0, 7), (1, 5), (2, 0), (3, 0), (4, 2), (5, 1)]


In [60]:
indexes = [i for (i, x) in enumerate(E) if x > 0]
n = E[list(np.nonzero(E))]
print(n)

[7 5 2 1]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  


In [44]:
#10 - Crear una matriz de identidad de 3x3.
id = np.eye(3,3)
print(id)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [53]:
#11 - Crear una matriz de 3x3x3 con valores aleatorios.
hola = np.random.random((3,3,3))
print(hola)

[[[0.77007084 0.85443007 0.57523548]
  [0.76995351 0.62679321 0.34517057]
  [0.00727718 0.18054321 0.36103301]]

 [[0.76319073 0.16311289 0.54231791]
  [0.40257723 0.990311   0.94765761]
  [0.40945365 0.22393306 0.42649348]]

 [[0.25103369 0.22426818 0.27148333]
  [0.40294569 0.0502001  0.21904501]
  [0.1493665  0.8471669  0.19272435]]]


In [56]:
#12 - Cree una matriz de 10x10 con valores aleatorios y encuentre el mínimo y el máximo.
diezydiez = np.random.random((10,10))
print("El mínimo de la matriz 10 x 10 es " + str(np.min(diezydiez)) + ".\nEl máximo es " + str(np.max(diezydiez)))

El mínimo de la matriz 10 x 10 es 0.0027850665736888214.
El máximo es 0.9969644547778831


In [62]:
#13 - Cree un vector aleatorio de tamaño 50 y encuentre el valor medio.
halvtreds = (np.random.random(50))
print("El valor medio del vector halvtreds es " + str(np.median(halvtreds)))

El valor medio del vector halvtreds es 0.5520648794775909


In [67]:
mat_al_2_8 = 6*np.random.random((3,3))+2
print(mat_al_2_8)

[[4.29553599 4.56109254 5.82423618]
 [3.689691   7.74834474 7.99434311]
 [3.97775574 4.98534504 4.14932278]]


In [92]:
#Genera una función matriz llamada matriznormal a la que podamos pedirle una 
#matriz cuadrada (con dimensión a especificar) 
#y cuyos datos sigan una distribución normal (con media y desviación típica a especificar).
#Asignad el valor 1 por defecto a la dimensión

def matriznormal(dimensiones = 1, mu = 1, sigma = 1):
  cuadro = sigma * np.random.randn(dimensiones, dimensiones) + mu 

  return cuadro

matriznormal(3,2,2)


array([[ 1.3507976 , -1.24366603,  4.43234966],
       [ 1.85257813,  6.53064502,  3.00429465],
       [ 2.613789  ,  3.7429887 ,  2.18424162]])

In [98]:
#14 - Cree una matriz de 6x6 con valores 1,2,3,4,5 justo debajo de la diagonal.
seisyseis = np.diag(1 + np.arange(5), k = -1)

print(np.diag(1 + np.array([1,2,3])))

[[2 0 0]
 [0 3 0]
 [0 0 4]]


In [99]:
#15 - Considere una matriz de formas (4,5,6), ¿cuál es el índice (x,y,z) del elemento número 57?
print(np.unravel_index(56,(4,5,6)))


(1, 4, 2)


In [ ]:
#16 - Normalice una matriz aleatoria de 10x10.


In [102]:
#18 - ¿Cómo encuentra valores comunes entre dos matrices?
m1 = np.random.randint(0,10,10)
m2 = np.random.randint(0,10,10)
print(np.intersect1d(m1,m2))


[1 5 7 8]


In [105]:
#19 - ¿Cómo obtener las fechas de ayer, hoy y mañana?
ayer    = np.datetime64('today') - np.timedelta64(1)
hoy     = np.datetime64('today')
mañana  = np.datetime64('today') + np.timedelta64(1)
print(ayer)


2022-06-05


In [106]:
#20 - ¿Cómo obtener todas las fechas correspondientes al mes de septiembre de 2020?
Z = np.arange('2020-09', '2020-10', dtype='datetime64[D]')
print(Z)

['2020-09-01' '2020-09-02' '2020-09-03' '2020-09-04' '2020-09-05'
 '2020-09-06' '2020-09-07' '2020-09-08' '2020-09-09' '2020-09-10'
 '2020-09-11' '2020-09-12' '2020-09-13' '2020-09-14' '2020-09-15'
 '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19' '2020-09-20'
 '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24' '2020-09-25'
 '2020-09-26' '2020-09-27' '2020-09-28' '2020-09-29' '2020-09-30']


In [ ]:
#21 - Extraiga la parte entera de una matriz aleatoria de números positivos usando 4 métodos diferentes.


In [107]:
#24 - Cree un vector aleatorio de tamaño 25 y ordénelo.
np.sort(np.random.random(25))


array([0.00097562, 0.00765981, 0.05535977, 0.06036471, 0.09457488,
       0.13186128, 0.16195106, 0.21523927, 0.30163177, 0.30779361,
       0.33878457, 0.34851706, 0.39762676, 0.45584582, 0.51920177,
       0.5803352 , 0.64434679, 0.69386284, 0.72502592, 0.74889053,
       0.75871941, 0.80502385, 0.9057873 , 0.91639811, 0.93933496])

#PANDA PART ADVANCED

In [108]:
#1 - Importa el paquete con el nombre "pd".
import pandas as pd

In [110]:
#2 - Imprime la versión instalada.
pd.__version__


'1.3.5'

In [131]:
#3 - Cree una serie desde un diccionario, desde una lista y desde un numpy array.

lista = [x for x in "adejfainjfsdiughajwefmew"]
nparray = np.arange(0,25) 
diccionario = dict(zip(lista, nparray))
serie1 = pd.Series(lista)
serie2 = pd.Series(nparray)
serie3 = pd.Series(diccionario)
serie4 = pd.Series(data = diccionario.keys(), index = diccionario.values())
print(serie3, serie4)

a    16
d    11
e    22
j    17
f    20
i    12
n     7
s    10
u    13
g    14
h    15
w    23
m    21
dtype: int64 16    a
11    d
22    e
17    j
20    f
12    i
7     n
10    s
13    u
14    g
15    h
23    w
21    m
dtype: object


In [124]:
#4 - Convierta el índice de una serie a una columna de un dataframe
df = serie.to_frame() #afegeix index a la columna
conindex = df.reset_index()


In [136]:
#5 - Combine varias series para formar un dataframe
df12 = pd.concat([serie1, serie2], axis = 1)
df21 = pd.DataFrame({"columna 1": serie1, "columna 2": serie2})
print(df21)

   columna 1  columna 2
0          a          0
1          d          1
2          e          2
3          j          3
4          f          4
5          a          5
6          i          6
7          n          7
8          j          8
9          f          9
10         s         10
11         d         11
12         i         12
13         u         13
14         g         14
15         h         15
16         a         16
17         j         17
18         w         18
19         e         19
20         f         20
21         m         21
22         e         22
23         w         23
24       NaN         24


In [147]:
#6 - Obtenga los items de la serie A no presentes en la serie B
A = pd.Series(["a", "b", "c"])
B = pd.Series([1, 2, "a"])
A[~A.isin(B)]


1    b
2    c
dtype: object

In [158]:
#7 - Obtenga la unión e intersección de dos series A y B.
A = pd.Series(["s", "w", "a"])
B = pd.Series(["d", "s", "a"])
union = pd.Series(np.union1d(A,B))
intersection = pd.Series(np.intersect1d(A,B))
print("This is the union ")
print(union)
print("This is the intersection ")
print(intersection)

This is the union 
0    a
1    d
2    s
3    w
dtype: object
This is the intersection 
0    a
1    s
dtype: object


In [169]:
#8 - Obtenga el valor mínimo, el percentil 25, la mediana, el percentil 75 y el máximo de una serie

S1 = pd.Series(np.random.RandomState(100).normal(10, 5, 25))
# Solución
percentiles = np.percentile(S1, q=[0, 25, 50, 75, 100])
print(percentiles)

(S1.describe())

[ 1.25117263  7.70986507 10.92259345 13.36360403 18.0949083 ]


count    25.000000
mean     10.435437
std       4.253118
min       1.251173
25%       7.709865
50%      10.922593
75%      13.363604
max      18.094908
dtype: float64

In [180]:
#9 - Obtenga la frecuencia de aparición de los elementos de una lista.
lista = [1, 2, 3, 5, 1, 1]
serie = pd.Series(np.take(list('abcdefghijklmnoprstuvwxyz'), np.random.randint(8, size=30)))
sf1 = pd.Series(lista)
print(serie.value_counts(normalize = True)*100)
(unico, contados) = np.unique(serie, return_counts = True)

print(f'Únicos: {unico}'),
print(f'Frecuencia: {contados}')

g    20.000000
f    16.666667
b    13.333333
a    13.333333
c    13.333333
h    10.000000
e     6.666667
d     6.666667
dtype: float64
Únicos: ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h']
Frecuencia: [4 4 4 2 2 5 6 3]


In [187]:
#10 - Mantenga de una lista los 3 términos que más aparecen. Renombre el resto de elementos a "otros".
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 9, [12]))
print(ser)
print(ser.value_counts()[:3])
print(~ser[ser.isin(ser)])

0     2
1     4
2     2
3     3
4     8
5     1
6     7
7     8
8     6
9     2
10    2
11    1
dtype: int64
2    4
8    2
1    2
dtype: int64


In [196]:
#11 - Convierta una serie en un dataframe con 5 filas y 3 columnas.
s1 = pd.Series(np.random.random(15))
df = pd.DataFrame(s1.values.reshape(5,3))
dfsol = pd.DataFrame(s1.values.reshape(5,3))
print(df, dfsol)

          0         1         2
0  0.641573  0.105225  0.829598
1  0.274952  0.822962  0.530697
2  0.459005  0.356496  0.405797
3  0.826247  0.211204  0.375023
4  0.650557  0.553275  0.655868           0         1         2
0  0.641573  0.105225  0.829598
1  0.274952  0.822962  0.530697
2  0.459005  0.356496  0.405797
3  0.826247  0.211204  0.375023
4  0.650557  0.553275  0.655868


In [198]:
# 12 - Extraer las de una serie dado una lista de posiciones.
# Entrada
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 1, 2, 25, 3]
print(ser[pos])

# Solution
ser.take(pos)

0     a
1     b
2     c
25    z
3     d
dtype: object


0     a
1     b
2     c
25    z
3     d
dtype: object

In [199]:
#13 - Obtener la posición de los items de la serie A en otra serie B.
# Entrada
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

# Solución 1
[np.where(i == ser1)[0].tolist()[0] for i in ser2]

# Solución 2
[pd.Index(ser1).get_loc(i) for i in ser2]

[5, 4, 0, 8]

In [ ]:
lista = []
np.where(lambda x: lista.append(x) if x == )

In [209]:
print(pd.Index(ser1))
ser1.to_frame#get_loc(10)

Int64Index([10, 9, 6, 5, 3, 1, 12, 8, 13], dtype='int64')


AttributeError: ignored

In [210]:
#14 - Calcule el Error Cuadrático Medio (SME en inglés) de dadas dos series.
# Entrada
verdad = pd.Series(range(10))
prediccion = pd.Series(range(10)) + np.random.random(10)

#solution
np.mean((verdad-prediccion)**2)


0.30512475019094965

In [218]:
#15 - Convertir el primer caracter de una serie en mayuúscula.
# Entrada
ser = pd.Series(['hola', 'me', 'llamo', 'Antonio'])
mayus = pd.Series([i.capitalize() for i in ser])
mayus = ser.str.title()
mayus = ser.apply([lambda x: x.capitalize()])
print(mayus)

0    <function <lambda> at 0x7f1a835d2170>
dtype: object


In [221]:
#16 - Calcular el número de caracteres de cada palabra en una serie.
# Entrada
ser = pd.Series(['hola', 'me', 'llamo', 'Antonio'])

# Solucion
solution1 = ser.map(lambda x: len(x))
solution2 = ser.apply(lambda x: len(x))
print(solution1, solution2)
ser.map(lambda x: x.capitalize())

0    4
1    2
2    5
3    7
dtype: int64 0    4
1    2
2    5
3    7
dtype: int64


0       Hola
1         Me
2      Llamo
3    Antonio
dtype: object

In [222]:
#17 - Dada una serie de fechas escritas como cadenas, páselas a timeseries.
# Entrada
ser = pd.Series(['01 Feb 2012', '02-03-2011', '20150503', '2016/04/04', '2018-05-05', '2018-06-06T12:20'])

# Solución
pd.to_datetime(ser)

0   2012-02-01 00:00:00
1   2011-02-03 00:00:00
2   2015-05-03 00:00:00
3   2016-04-04 00:00:00
4   2018-05-05 00:00:00
5   2018-06-06 12:20:00
dtype: datetime64[ns]

In [223]:
#18 - Obtenga el día del mes, el número de la semana y el día del año a partir de una serie de cadenas de fechas.
# Entrada
ser = pd.Series(['01 Feb 2012', '02-03-2011', '20150503', '2016/04/04', '2018-05-05', '2018-06-06T12:20'])

# Solución
from dateutil.parser import parse
ser_ts = ser.map(lambda x: parse(x))

# Día del mes
print("Fecha: ", ser_ts.dt.day.tolist())

# Semana number
print("Número de semana: ", ser_ts.dt.weekofyear.tolist())

# Día del año
print("Día del año: ", ser_ts.dt.dayofyear.tolist())

Fecha:  [1, 3, 3, 4, 5, 6]
Número de semana:  [5, 5, 18, 14, 18, 23]
Día del año:  [32, 34, 123, 95, 125, 157]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  del sys.path[0]
