# **Colección de ejercicios de Numpy**

In [ ]:
# Importa el paquete con el nombre "np"
import numpy as np

In [ ]:
# Imprime la versión instalada
print(np.__version__)
np.show_config()

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

In [ ]:
#Cree un vector nulo de tamaño 10 pero el quinto valor tiene de valor 1
T= np.zeros(10)
T[4] = 1
print(T)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# Calcular la desviación típica de T
# Mostrar la media y desviación Típica de T
np.std(T)
print("La Media de T corresponde a : " + str(np.mean(T)) + " \nLa Desviación Típica de T corresponde a : " + str(np.std(T)))

La Media de T corresponde a : 0.1 
La Desviación Típica de T corresponde a : 0.30000000000000004


In [ ]:
# Cree un vector con valores que van de 10 a 49.
np.arange(10,50,dtype=int)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
# Generar un vector con 7 elementos equidistantes entre el 2 y el 16. Dadle la vuelta a este vector
Z=np.linspace(1, 16, num=7) #lisnpace sirve para generar las distancias equidistantes en una línea recta, para un plano cartesiano se puede usar Geomspace
cZ = Z[::-1]
print(Z)

[16.  13.5 11.   8.5  6.   3.5  1. ]


In [ ]:
# Crear una matriz de 3x3 con valores que van de 0 a 8
Mtrz= np.arange(0,9).reshape(3, 3)
print(Mtrz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Encuentre los índices de elementos distintos de cero de [7,5,0,0,2,1]
a = np.array([7,5,0,0,2,1])
print(np.where(a!=0)[0])


[0 1 4 5]


In [ ]:
# Imprimir los números a los que hace referencia los índices anteriores
e = [x for x in a if x !=0]
print(e)

[7, 5, 2, 1]


In [ ]:
# crear una matriz de 3x3x3 de números aleatorios  
np.random.rand(3,3,3)

array([[[0.71774488, 0.82434706, 0.46351772],
        [0.07600248, 0.52042787, 0.52663674],
        [0.79822934, 0.51963899, 0.01704578]],

       [[0.33682337, 0.8991137 , 0.11906562],
        [0.17620498, 0.85986998, 0.22892184],
        [0.7374658 , 0.00202712, 0.90082193]],

       [[0.5041498 , 0.05217074, 0.52065317],
        [0.28948111, 0.65560462, 0.15216891],
        [0.72602154, 0.46860242, 0.83160652]]])

In [ ]:
# crear una matriz de 10x 10 y luego calcular el número máximo y el mínimo

Mtale= np.random.rand(10,10)
print(Mtale)


[[0.84687798 0.01505968 0.17154171 0.91244338 0.48410805 0.07190603
  0.25457919 0.93891419 0.25766586 0.84713849]
 [0.97935712 0.4255936  0.17540874 0.81610422 0.50846568 0.64096787
  0.15806809 0.00286956 0.68184866 0.73752375]
 [0.82866833 0.11451417 0.79158757 0.24632414 0.2554697  0.54950541
  0.239024   0.80879829 0.3774388  0.64802331]
 [0.24809862 0.49929472 0.95994007 0.6705622  0.05189944 0.74470876
  0.6984499  0.56146051 0.32353567 0.56699982]
 [0.91806347 0.34792807 0.44082459 0.62222963 0.7623456  0.07041946
  0.74644215 0.27810236 0.39732972 0.12285503]
 [0.78482385 0.28801941 0.71720641 0.68199927 0.3567065  0.70251863
  0.96694332 0.63429285 0.42519466 0.63895974]
 [0.95147392 0.49652804 0.74242873 0.49641927 0.37481422 0.93928634
  0.44674814 0.20757652 0.06965245 0.29810542]
 [0.84080658 0.9315639  0.95276405 0.1256852  0.19132758 0.47474523
  0.3490309  0.36526917 0.58371195 0.94088179]
 [0.28966517 0.6537854  0.86476132 0.34691628 0.91140366 0.1743925
  0.16383687 

In [ ]:
print("El maximo de la matriz es : "+ str(np.max(Mtale))) 
print("El maximo de la matriz es : "+ str(np.min(Mtale))) 

El maximo de la matriz es : 0.9793571228686861
El maximo de la matriz es : 0.0028695595126385642


In [ ]:
# Generar una matriz llamada "mat_al_2_8" de 3 x 3 , con números aleatorios entre el 2 y el 8
mat_al_2_8 = np.random.randint(2,8, size=(3, 3)) 
print(mat_al_2_8)

[[6 5 2]
 [4 2 5]
 [4 7 7]]


* Genera una función matriz llamada matriznormal a la que podamos pedirle una matriz cuadrada (con dimensión a especificar) y cuyos datos sigan una distribución normal (con media y desviación típica a especificar).

In [ ]:
def matriz_normal2 (media,desviacion,dimension=1):
  numero_aleatorio = desviacion*np.random.rand(dimension**2) + media
  return numero_aleatorio.reshape(dimension,dimension)


In [ ]:
print(matriz_normal2(5,2,3))

[[5.07231495 6.48310649 5.52293283]
 [6.65987466 6.8721194  5.33875911]
 [6.16841315 6.01711884 6.01791204]]


In [ ]:
# Cree una matriz de 6x6 con valores 1,2,3,4,5 justo debajo de la diagonal.
Z = np.diag(np.arange(5)+(1),k=-1)
print(Z)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


In [ ]:
# Considere una matriz de formas (4,5,6), ¿cuál es el índice (x,y,z) del elemento número 57?

print(np.unravel_index(56,(4,5,6)))


(1, 4, 2)


In [ ]:
# Normalice una matriz aleatoria de 10x10
Z = np.random.random((10,10))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.81451362  0.85831135  0.95972765 -0.31550809  1.08981918  0.62738116
   0.62922665  0.50955987 -0.56208358  1.4414846 ]
 [ 0.84145632 -0.06857573 -0.5366793   0.02834056  0.05350114  1.3036126
  -0.18648876 -0.91611043  1.45040004  1.45618418]
 [ 0.04245318 -0.80548039  1.05327921  1.07216454  0.75710095  1.27898032
  -1.62348333  1.50663437 -1.19305258  0.06244007]
 [ 0.03067916  0.83788209 -0.13432763  1.24225797 -1.20637107  1.28645277
  -1.44528096  0.17025774  1.23078539  0.81207867]
 [-0.70316353  0.58145758 -1.1566975  -0.53094586  0.32314546 -1.32730175
   0.52217454 -0.60511556 -0.67733679  1.57617655]
 [-0.49522694 -0.87358558  1.53639522 -1.4369694  -1.06351165 -1.31113183
  -0.81292455 -1.6848501   0.92838243  0.82905471]
 [-0.53971045  0.77455301  1.19781054 -1.30886994 -1.24610164 -1.42483476
   0.46525164 -0.78092942 -1.10194252 -1.21782223]
 [ 0.33912057 -0.41392086  0.66988179  1.12270739  0.87658537  0.04578492
  -1.43027375 -0.33491666  1.07357851 -1.46756078]
 

In [ ]:
#Multiplique una matriz de 3x2 por una matriz de 2x5.

Z = np.dot(np.ones((3,2)), np.ones((2,5)))
print(Z)

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [ ]:
#  ¿Cómo obtener las fechas de ayer, hoy y mañana?

ayer    = np.datetime64('today') - np.timedelta64(1)
hoy     = np.datetime64('today')
mañana  = np.datetime64('today') + np.timedelta64(1)


In [ ]:
# ¿Cómo obtener todas las fechas correspondientes al mes de septiembre de 2020?

Z = np.arange('2020-09', '2020-10', dtype='datetime64[D]')
print(Z)

['2020-09-01' '2020-09-02' '2020-09-03' '2020-09-04' '2020-09-05'
 '2020-09-06' '2020-09-07' '2020-09-08' '2020-09-09' '2020-09-10'
 '2020-09-11' '2020-09-12' '2020-09-13' '2020-09-14' '2020-09-15'
 '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19' '2020-09-20'
 '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24' '2020-09-25'
 '2020-09-26' '2020-09-27' '2020-09-28' '2020-09-29' '2020-09-30']


In [ ]:
# Extraiga la parte entera de una matriz aleatoria de números positivos usando 4 métodos diferentes.

Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))



[1. 9. 9. 1. 8. 3. 6. 4. 3. 4.]
[1. 9. 9. 1. 8. 3. 6. 4. 3. 4.]
[1. 9. 9. 1. 8. 3. 6. 4. 3. 4.]
[1 9 9 1 8 3 6 4 3 4]
[1. 9. 9. 1. 8. 3. 6. 4. 3. 4.]


In [ ]:
# Cree una matriz de 10x10 con valores de fila que van de 0 a 9.

Z = np.zeros((10,10))
Z += np.arange(10)
print(Z)

[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]


In [ ]:
# Cree un vector de tamaño 5 con valores que van de 0 a 1, ambos excluidos.
Z = np.linspace(0,1,6,endpoint=False)[1:]
print(Z)

[0.16666667 0.33333333 0.5        0.66666667 0.83333333]


In [ ]:
# Cree un vector aleatorio de tamaño 25 y ordénelo.
Z = np.random.random(25)
Z.sort()
print(Z)


[0.01721521 0.05965137 0.24065327 0.28563708 0.28939351 0.35178909
 0.38449446 0.41312286 0.53777445 0.58682756 0.59528361 0.62223317
 0.63698638 0.65454536 0.6625654  0.69966321 0.73600738 0.7787931
 0.78527482 0.81660949 0.85402668 0.87017483 0.90279232 0.93889752
 0.97844129]


In [ ]:
# Sume un vector usando np.add.reduce.

Z = np.arange(20)
np.add.reduce(Z)

190

In [ ]:
#  Considere dos matrices aleatorias A y B, verifique si son iguales.

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Si son identicas en forma pero no tienen los mismos valores (hay tolerancia).
equal = np.allclose(A,B)
print(equal)

# Si son identicas en forma y además tienen los mismos valores (no hay tolerancia).
equal = np.array_equal(A,B)
print(equal)

False
False


In [ ]:
# Cree un vector aleatorio de tamaño 25 y reemplace el valor máximo por 0.
Z = np.random.random(25)
Z[Z.argmax()] = 0
print(Z)


[0.39069593 0.95687551 0.47191724 0.19045238 0.2460326  0.07723248
 0.0204837  0.95889858 0.06814277 0.42827407 0.43198751 0.47964495
 0.45250611 0.00493347 0.25421768 0.46531074 0.95323717 0.56960709
 0.17298497 0.         0.42931769 0.79529614 0.57020114 0.58765712
 0.47598239]


In [ ]:
# ¿Cómo imprimir todos los valores de una matriz?
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

In [ ]:
# ¿Cómo encontrar el valor más cercano, a un escalar dado, en un vector?

HH = np.arange(100)
print(HH)




[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
JJ = np.random.uniform(0,100)
print(JJ)



32.61006877885077


In [ ]:
index = (np.abs(HH-JJ)).argmin()
print(HH[index])

33


# Ejercicios Pandas

In [1]:
# Importar Pandas".
import pandas as pd



In [2]:
#Imprimir la versión instalada.
pd.__version__

'1.3.5'

In [5]:
# Cree una serie desde un diccionario, desde una lista y desde un numpy array.
import numpy as np
# Entrada:
mi_lista = list('abcedfghijklmnopqrstuvwxyz')
np_array = np.arange(26)
diccionario = dict(zip(mi_lista, np_array))

# Salida:
ser1 = pd.Series(mi_lista)
ser2 = pd.Series(np_array)
ser3 = pd.Series(diccionario)
print(ser3.head())

a    0
b    1
c    2
e    3
d    4
dtype: int64


In [6]:
# Convierta el índice de una serie a una columna de un dataframe
# Entrada:
mi_lista = list('abcedfghijklmnopqrstuvwxyz')
np_array = np.arange(26)
diccionario = dict(zip(mi_lista, np_array))
ser3 = pd.Series(diccionario)

# Salida
df = ser3.to_frame().reset_index()
print(df.head())

  index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4


In [9]:
# Combinar varias series para formar un dataframe
# Entrada
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

# Solución 1
df = pd.concat([ser1, ser2], axis=1)

# Solución 2
df = pd.DataFrame({'col1': ser1, 'col2': ser2})
print(df.head())

  col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4


In [10]:
# Obtener los items de la serie A no presentes en la serie B
A = pd.Series(["a", "b", "c"])
B = pd.Series([1, 2, "a"])
A[~A.isin(B)]



1    b
2    c
dtype: object

In [12]:
# Obtenga la unión e intersección de dos series A y B.


# Entrada
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

# Solución
union = pd.Series(np.union1d(ser1, ser2))  
interseccion = pd.Series(np.intersect1d(ser1, ser2))  

union
interseccion



0    4
1    5
dtype: int64

In [13]:
# Obtenga el valor mínimo, el percentil 25, la mediana, el percentil 75 y el máximo de una serie



# Entrada
serie_ejemplo = np.random.RandomState(100)
serie_ejemplo = pd.Series(serie_ejemplo.normal(10, 5, 25))

# Solución
np.percentile(serie_ejemplo, q=[0, 25, 50, 75, 100])



array([ 1.25117263,  7.70986507, 10.92259345, 13.36360403, 18.0949083 ])

In [14]:
# Obtenga la frecuencia de aparición de los elementos de una lista.



# Entrada
serie = pd.Series(np.take(list('abcdefghijklmnoprstuvwxyz'), np.random.randint(8, size=30)))

# Solucion
serie.value_counts()



h    7
e    4
g    4
d    4
a    3
f    3
c    3
b    2
dtype: int64

In [15]:
# Mantenga de una lista los 3 términos que más aparecen. Renombre el resto de elementos a "otros".
# Entrada
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

# Solución
print("Top 3:", ser.value_counts())
ser[~ser.isin(ser.value_counts().index[:3])] = 'Otros'
ser


Top 3: 2    4
1    3
3    3
4    2
dtype: int64


0         2
1     Otros
2         2
3         1
4         3
5         2
6         1
7         3
8         2
9         1
10    Otros
11        3
dtype: object

In [16]:
# Convierta una serie en un dataframe con 5 filas y 3 columnas.



# Entrada
ser = pd.Series(np.random.randint(1, 10, 15))

# Solucion
df = pd.DataFrame(ser.values.reshape(5,3))
print(df)



   0  1  2
0  6  9  2
1  5  2  5
2  5  9  7
3  5  5  7
4  3  2  1


In [17]:
# Extraer las de una serie dado una lista de posiciones.


# Entrada
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 1, 2, 25, 3]

# Solution
ser.take(pos)



0     a
1     b
2     c
25    z
3     d
dtype: object

In [18]:
# Obtener la posición de los items de la serie A en otra serie B.



# Entrada
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

# Solución 1
[np.where(i == ser1)[0].tolist()[0] for i in ser2]

# Solución 2
[pd.Index(ser1).get_loc(i) for i in ser2]



[5, 4, 0, 8]

In [19]:
# Calcule el Error Cuadrático Medio (SME en inglés) de dadas dos series.
# Entrada
verdad = pd.Series(range(10))
prediccion = pd.Series(range(10)) + np.random.random(10)

# Solución
np.mean((verdad-prediccion)**2)

0.353683432047267

In [21]:
# Convertir el primer caracter de una serie en mayuúscula.



# Entrada
ser = pd.Series(['hola', 'me', 'llamo', 'Luis'])

#Solución
pd.Series([i.title() for i in ser])




0     Hola
1       Me
2    Llamo
3     Luis
dtype: object

In [23]:
#  Calcular el número de caracteres de cada palabra en una serie.


# Entrada
ser = pd.Series(['hola', 'me', 'llamo', 'Luis'])

# Solucion
ser.map(lambda x: len(x))



0    4
1    2
2    5
3    4
dtype: int64

In [24]:
# Dada una serie de fechas escritas como cadenas, páselas a timeseries.



# Entrada
ser = pd.Series(['01 Feb 2012', '02-03-2011', '20150503', '2016/04/04', '2018-05-05', '2018-06-06T12:20'])

# Solución
pd.to_datetime(ser)



0   2012-02-01 00:00:00
1   2011-02-03 00:00:00
2   2015-05-03 00:00:00
3   2016-04-04 00:00:00
4   2018-05-05 00:00:00
5   2018-06-06 12:20:00
dtype: datetime64[ns]

In [25]:
# Obtenga el día del mes, el número de la semana y el día del año a partir de una serie de cadenas de fechas.

# Entrada
ser = pd.Series(['01 Feb 2012', '02-03-2011', '20150503', '2016/04/04', '2018-05-05', '2018-06-06T12:20'])

# Solución
from dateutil.parser import parse
ser_ts = ser.map(lambda x: parse(x))

# Día del mes
print("Fecha: ", ser_ts.dt.day.tolist())

# Semana number
print("Número de semana: ", ser_ts.dt.weekofyear.tolist())

# Día del año
print("Día del año: ", ser_ts.dt.dayofyear.tolist())

Fecha:  [1, 3, 3, 4, 5, 6]
Número de semana:  [5, 5, 18, 14, 18, 23]
Día del año:  [32, 34, 123, 95, 125, 157]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  
