# NumPy 
numPy es una librería de álgebra lineal para Python. La razón por la que es tan importante par ala ciencia de datos es que casi todas las librerías del ecosistema PyData están construidas sobre numPy. Una de las razones de su uso es su rapidez, ya que está construida sobre C.

## Usar NumPy

Una vez hayamos instalado numPy, la importamos como sigue:

In [1]:
#!pip install numpy
import numpy as np

Por su extendido uso, numPy posee incontables funcionalidades, por lo que es impensable cubrir todas ellas. Sin embargo, daremos nociones de su uso sobre los objetos más trascendentes, que son los vectores, matrices, `arrays` en un contexto más genérico, y generación de números aleatorios.

# Numpy Arrays

Los `arrays` son los principales objetos que dispone numPy, y sobre los cuales se pueden implementar multitud de algoritmos via vectorización. En muchos casos, utilizaremos `arrays` de dimensión 1 (vectores) y 2 (matrices), aunque no es infrecuente encontrarse casos en los que tenga dimensión mayor, dependiendo del contexto de nuestro problema (e.g., procesamiento de imágenes).

Empecemos nuestra instroducción aprendiendo a generar estos objetos.

## Crear NumPy Arrays

### A partir de una lista

Una de las maneras más habituales de inicializar un `numpy.array` es a través de una lista de Python, entendiéndose la concatenación de las mismas como un aumento progresivo en la dimensionalidad.

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Métodos implementados

Si, por el contrario, necesitamos construir `arrays` con una dimensionalidad específica (para inicializar algoritmos,...), es muy habitual recurrir a métodos ya implementados que nos permiten esta flexibilidad.

### arange

Devuelve un vector equiespaciado entre dos números.

```python
np.arange(initial_number = 0, final_number, step = 1)
```

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros y ones

Generamos `arrays` de ceros y unos respectivamente, con la forma especificada en una tupla.

In [ ]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [ ]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [ ]:
np.ones(3)

array([ 1.,  1.,  1.])

In [ ]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### linspace
Devuelve un vector de números comprendidos entre el dato inicial y final, tan amplio como un parámetro especificado.

```python
np.linspace(initial_number, final_number, length)
```

In [ ]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [ ]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

## eye

Crea una matriz identidad.

In [ ]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Random 

numPy también tiene una gran variedad de métodos para generar números aleatorios:

### rand
Genera un `array` de la forma especificada, con valores aleatorios uniformemente distribuídos en el intervalo ``[0, 1)``.

In [ ]:
np.random.rand(2)

array([ 0.11570539,  0.35279769])

In [ ]:
np.random.rand(5,5)

array([[ 0.66660768,  0.87589888,  0.12421056,  0.65074126,  0.60260888],
       [ 0.70027668,  0.85572434,  0.8464595 ,  0.2735416 ,  0.10955384],
       [ 0.0670566 ,  0.83267738,  0.9082729 ,  0.58249129,  0.12305748],
       [ 0.27948423,  0.66422017,  0.95639833,  0.34238788,  0.9578872 ],
       [ 0.72155386,  0.3035422 ,  0.85249683,  0.30414307,  0.79718816]])

*¿Y si queremos obtener valores uniformemente distribuidos en el intervalo [a,b)?*

In [ ]:
a = 1
b = 5
#(b-a)*np.random.rand(5,5)+a

array([[3.1810784 , 2.92116665, 1.66623257, 1.82619903, 1.00287646],
       [1.89257436, 3.89334537, 3.28541704, 4.85957729, 3.85905688],
       [3.45468605, 2.17405343, 1.51280297, 1.06390386, 1.04207551],
       [3.40187475, 3.9185836 , 2.53721727, 2.25857667, 1.95887948],
       [3.20769835, 2.44288468, 2.18016741, 1.73002333, 4.4945557 ]])

### randn

Devuelve una muestra de números normalmente distribuidos.

In [ ]:
np.random.randn(2)

array([-0.27954018,  0.90078368])

In [ ]:
np.random.randn(5,5)

array([[ 0.70154515,  0.22441999,  1.33563186,  0.82872577, -0.28247509],
       [ 0.64489788,  0.61815094, -0.81693168, -0.30102424, -0.29030574],
       [ 0.8695976 ,  0.413755  ,  2.20047208,  0.17955692, -0.82159344],
       [ 0.59264235,  1.29869894, -1.18870241,  0.11590888, -0.09181687],
       [-0.96924265, -1.62888685, -2.05787102, -0.29705576,  0.68915542]])

*¿Qué pasa si queremos una distribución normal "no estándar"?*

In [ ]:
mu = 5
sigma = 3
#sigma*np.random.randn(5,5) + mu

array([[ 4.4074478 ,  2.91316296,  4.17065728,  0.76731403,  6.42334656],
       [-0.47688024,  2.85426973,  4.60544258,  4.89049264,  5.35918162],
       [ 8.37565466, 13.20579711,  6.43134357,  3.98533958,  1.76480726],
       [ 2.93351259,  6.70042146,  4.18845583,  3.88761579,  5.1315325 ],
       [ 5.85477468,  4.24306987,  3.92650713,  1.24097779,  7.81221815]])

### randint
Devuelve enteros desde el valor `low` (incluido) hasta `high` (excluido).

In [ ]:
np.random.randint(1,100)

44

In [ ]:
np.random.randint(1,100,10)

array([13, 64, 27, 63, 46, 68, 92, 10, 58, 24])

### Más distribuciones

In [ ]:
help(np.random)

## Atributos y métodos

Veamos cuáles son algunos de los más importantes en el día a día para trabajar con `arrays`:

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

## Reshape

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin


In [ ]:
ranarr

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

In [ ]:
ranarr.max()

49

In [ ]:
ranarr.argmax()

4

In [ ]:
ranarr.min()

2

In [ ]:
ranarr.argmin()

5

## Shape

Shape es un atributo que nos indica la forma del `array`

In [ ]:
# Vector
arr.shape

(25,)

In [ ]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(25,1).shape

(25, 1)

### dtype

Otro atributo importante es el tipo de dato que estamos manejando

In [ ]:
arr.dtype

#NumPy indexado y filtrado

En esta sección, veremos cómo seleccionar fragmentos de `arrays` basados en distintos criterios:

In [ ]:
arr = np.arange(0,11)

## Bracket Indexing
La manera más sencilla es filtrar a través de los índices, como en las listas.

In [ ]:
arr[8]

In [ ]:
arr[1:5]

## Broadcasting

Estos objetos se diferencian de las listas en que podemos asignar valores a elementos del `array` mediante filtros:

In [ ]:
arr[0:5]=100
print(arr)

In [ ]:
# Recuperamos el array inicial
arr = np.arange(0,11)
print(arr)

Un hecho importante es que, cuando generamos una nueva variable a partir de un fragmento de otro `array`, debemos especificarlo mediante el método `.copy()`, pues si no lo que haremos será manipular un fragmento de la variable original. Esta implementación evita sobrecostes de memoria.

In [5]:
#"Creamos" una variable que es un fragment
slice_of_arr = arr[0:6]
print(slice_of_arr)

[99 99 99 99 99 99  6  7  8  9 10]


In [4]:
#La modificamos
slice_of_arr[:]=99

#Vemos que el array original se ha modificado
print(arr)

array([99, 99, 99, 99, 99, 99])

In [ ]:
#Para obtener una copia y trabajar sobre ella de forma independiente, debemos especificarlo
arr_copy = arr.copy()
print(arr_copy)

## Indexado de matrices (arrays 2-dimensionales)

El formato general es **arr_2d[row][col]** o **arr_2d[row,col]**, aunque es preferible usar la segunda notación por claridad, y para casos más genéricos.

In [17]:
arr_2d = np.arange(0,9).reshape(3,3)
print(arr_2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
np.arange(0,1)

array([0])

In [19]:
#Tip: Cuando queramos obtener el valor de un único elemento pero en formato array, en alguna de las dimensiones
#     debemos introducir el índice en formato lista, o de la forma que sigue:
print(arr_2d[1,[0]]) #Formato lista
print(arr_2d[1,0:1]) #Con :

[3]
[3]


Para hacer filtrados más extensos, usamos listas de índices, o bien si son consecutivos podemos usar la notación **arr_2d[first_index:last_index,:]**

In [20]:
# Matrix 2x2 de la esquina superior derecha
arr_2d[:2,1:]

array([[1, 2],
       [4, 5]])

### Fancy Indexing

Fancy indexing hace referencia a la posibilidad de poder filtrar filas y/o columnas, ordenándolas en el orden que se prefiera.

In [30]:
arr2d = np.random.randint(low = 0, high = 100, size = 25).reshape(5,5)
print(arr2d)

[[11  9 92 62 15]
 [84 19 97  9 71]
 [12 81 60 92 89]
 [72  6 62 83 51]
 [71  2 26 82 36]]


In [32]:
#Permutamos filas
arr2d[[3,2,1],:]

array([[72,  6, 62, 83, 51],
       [12, 81, 60, 92, 89],
       [84, 19, 97,  9, 71]])

## Filtrado lógico

Finalmente, podemos usar booleanos para filtrar elementos de un `array`

In [33]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [34]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [35]:
bool_arr = arr>4
print(arr[bool_arr])

[ 5  6  7  8  9 10]


In [36]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Operaciones con NumPy

## Aritmética

In [39]:
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [40]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [41]:
# La indeterminación 0/0 no devuelve un error, si no una advertencia y un objeto np.nan
arr/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [43]:
# De nuevo, la división por cero muestra otro warning y un objeto inf
1/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [44]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [51]:
mat1 = np.random.rand(3,4)
mat2 = np.random.rand(4,2)
print('Matriz 1:\n{}'.format(mat1))
print('\nMatriz 2:\n{}'.format(mat2))
mult_matrix = np.matmul(mat1,mat2)
#mult_matrix = np.dot(mat1,mat2)
print('\nMatrices multiplicadas:\n{}'.format(mult_matrix))

Matriz 1:
[[0.99657771 0.35547073 0.68958416 0.68671249]
 [0.77678433 0.20057188 0.4576166  0.98924959]
 [0.04767956 0.25181396 0.29884241 0.59012041]]

Matriz 2:
[[0.91033292 0.51800728]
 [0.67095778 0.38664478]
 [0.73302668 0.16320122]
 [0.93834027 0.18698869]]

Matrices multiplicadas:
[[2.29557692 0.89462385]
 [2.10540553 0.73959208]
 [0.98515402 0.2811782 ]]


In [ ]:
help(np.linalg)

## Universal Array Functions

NumPy tiene también implementadas numerosas [funciones universales para arrays](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), que nos permiten realizar operciones matemáticas sobre los elementos de un array:

In [71]:
arr = np.random.randint(low = 1, high = 10, size = 9).reshape(3,3)
print('Matriz original:\n{}'.format(arr))
sq_root_arr = np.sqrt(arr)
print('\nMatriz con raíces cuadradas:\n{}'.format(sq_root_arr))
exp_arr = np.exp(arr)
print('\nMatriz con exponenciales:\n{}'.format(exp_arr))
sin_arr = np.sin(arr)
print('\nMatriz con senos:\n{}'.format(sin_arr))
log_arr = np.log(arr)
print('\nMatriz con logaritmos:\n{}'.format(log_arr))
log_st_arr = np.log1p(arr)
print('\nMatriz con log(x+1):\n{}'.format(log_st_arr))
exp_st_arr = np.expm1(arr)
print('\nMatriz con exp(x)-1:\n{}'.format(exp_st_arr))

Matriz original:
[[6 1 2]
 [6 2 4]
 [2 4 7]]

Matriz con raíces cuadradas:
[[2.44948974 1.         1.41421356]
 [2.44948974 1.41421356 2.        ]
 [1.41421356 2.         2.64575131]]

Matriz con exponenciales:
[[ 403.42879349    2.71828183    7.3890561 ]
 [ 403.42879349    7.3890561    54.59815003]
 [   7.3890561    54.59815003 1096.63315843]]

Matriz con senos:
[[-0.2794155   0.84147098  0.90929743]
 [-0.2794155   0.90929743 -0.7568025 ]
 [ 0.90929743 -0.7568025   0.6569866 ]]

Matriz con logaritmos:
[[1.79175947 0.         0.69314718]
 [1.79175947 0.69314718 1.38629436]
 [0.69314718 1.38629436 1.94591015]]

Matriz con log(x+1):
[[1.94591015 0.69314718 1.09861229]
 [1.94591015 1.09861229 1.60943791]
 [1.09861229 1.60943791 2.07944154]]

Matriz con exp(x)-1:
[[ 402.42879349    1.71828183    6.3890561 ]
 [ 402.42879349    6.3890561    53.59815003]
 [   6.3890561    53.59815003 1095.63315843]]


In [60]:
np.max(arr)

6