# NumPy Ejercicios

#### Importar librería



In [1]:
# Tambien podria ser como '!pip install numpy'
import numpy as np

#### Crear una array (unidimensional) con 10 ceros

In [3]:
np.zeros (10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Resultado esperado:
```python
array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])
```

#### Crear un array (unidimensional) con 10 unos

In [4]:
np.ones (10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Resultado esperado:
```python
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
```

#### Crear un array con 10 cincos

In [13]:
np.ones(10)*5

# mis_diesses = np.full((1, 10), 5)
# print(mis_diesses)
# otra seria np.full (20,5,dtype=float)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Resultado esperado:
```python
array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])
```

#### Crear un array (unidimensional) con los números enteros desde 10 hasta 50

In [16]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Resultado esperado:
```python
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])
```

#### Crear un array (unidimensional) con los enteros pares comprendidos entre 10 y 50

In [19]:
np.arange(10,52,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Resultado esperado:
```python
array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])
```

#### Crear una matriz 3x3 con los enteros comprendidos entre 0 y 8

In [10]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Resultado esperado:
```python
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
```

# Ejercicio extra:

Cree una función que nos diga si la lista o matriz que estamos metiendo a la función es transformable en una matriz cuadrada de un determinado orden.



* Comprueba si se cumple cumple la condición, y en dicho caso, devuelve la matriz cuadrada.



* En caso contrario, devuelve un error. `raise ValueError()`

In [ ]:
def transformar_lista_array(lista_o_matriz):

    if type(lista_o_matriz) == list:

        matrix = np.array(lista_o_matriz)
    n = np.sqrt(len(matrix))
    
    if n%1 == 0 
        
        return matrix.reshape((int(n), int(n)))
    else:

        matrix = np.array(lista_o_matriz)

    type(np.sqrt(len(matrix))) == int


#### Crear una matriz identidad de orden 3

In [14]:
np.eye(3)
# np.diag([1, 1, 1])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Resultado esperado:
```python
array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])
```

#### Generar un número aleatorio proveniente de una distribución uniforme, entre 0 y 1

In [30]:
np.random.rand()

0.05425580392971052

In [32]:
from numpy.random import default_rng

# Es un generador de numeros, que permite poner una semilla, consiguiendo así
# el mismo valor 'random'. El 'seed=44' no es necesario, y nos daria siempre valores aleatorios

default_rng(seed=44).random((1))

array([0.12256551])

#### Obtener 25 números aleatorios procedentes de una distribución normal estandar

In [21]:
np.random.randn(25)

array([ 1.33413653, -0.73272638, -0.37679651, -0.5280667 ,  1.05885729,
       -0.15365287,  0.68931286,  1.51853472,  0.22206824, -0.55399965,
        1.08446024,  1.67908642, -1.3477471 ,  0.2818987 ,  0.38020234,
       -1.3573734 , -1.14990272, -0.08733877,  0.79539534, -0.33060989,
       -1.63285702,  0.19027232, -0.7443918 ,  0.63960554, -0.45739852])

#### Genera la siguiente matriz:
```python
array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])
```

In [41]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Crear un vector de 20 valores equidistantes entre 0 y 1

In [25]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Resultado esperado:
```python
array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])
```

## Numpy Indexado y filtrado

Dada la siguiente matriz, realice las operaciones pertinentes para obtener la salida que se pide:

In [36]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**Primer ejercicio**

In [50]:
mat [2:,1:] # Primero metemos la fila y segundo la columna, siendo ambas incluidas

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

*Resultado esperado:*


```
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```



**Segundo ejercicio**

In [51]:
mat [3,4]

20

*Resultado esperado:*

```
20
```



**Tercer ejercicio**

In [54]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

*Resultado esperado:*

```
array([[ 2],
       [ 7],
       [12]])
```



**Cuarto ejercicio**

In [57]:
mat [4,:]

array([21, 22, 23, 24, 25])

*Resultado esperado:*


```
array([21, 22, 23, 24, 25])
```



**Quinto ejercicio**

In [60]:
mat [3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

*Resultado esperado:*


```python
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```



### Realice los siguiente cálculos:

#### Obtenga la suma de todos los valores de la matriz

In [65]:
# Hacemos la suma de la suma de las columnas

sum(sum(mat))

# np.sum(mat) 

325

In [66]:
np.sum(mat, axis=1) # me suma por filas al meter el axis/eje

array([ 15,  40,  65,  90, 115])

*Resultado esperado:*


```python
325
```

#### Calcule la desviación típica de los valores de la matriz

In [67]:
np.std(mat)

7.211102550927978

In [68]:
# La media seria:

np.mean(mat)

13.0

*Resultado esperado:*


```python
7.211102550927978
```

#### Sume los valores por columnas



In [70]:
sum (mat)


array([55, 60, 65, 70, 75])

In [71]:
np.sum (mat, axis=0)

array([55, 60, 65, 70, 75])

*Resultado esperado:*


```python
array([55, 60, 65, 70, 75])
```

## Avanzado

### Obtenga el rango de la siguiente matriz cuadrada:

```python
Z = np.random.uniform(0,1,(10,10))
```

*(Indicaciones: Al ser cuadrada, podemos analizar sus autovalores)*

In [72]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


### Implemente el algoritmo k-NN (*k Nearest Neighbours*)

*Indicaciones: Este algoritmo de aprendizaje supervisado consiste en asignar, a cada elemento, la media de las labels de los k vecinos más cercanos que tenga dicho elemento.*


*Veámoslo sobre un ejemplo: Supongamos que tenemos una serie de variables comportamentales de estudiantes (visualizaciones, ediciones, creaciones y descargas):*

```python
array([[19,  7, 12,  4],
       [19,  0,  7,  9],
       [17, 12, 17,  6],
       [ 8, 10,  1, 12],
       [ 9,  6,  0, 15],
       [11, 18,  1, 14],
       [16,  8, 12,  1],
       [ 2, 13,  6, 17],
       [ 0,  7, 13,  8],
       [15,  9, 10, 15]])
```

*Asociado a estos datos, tenemos además una calificación del estudiante a final de curso:*

```python
array([[6],
       [4],
       [7],
       [4],
       [3],
       [9],
       [9],
       [5],
       [3],
       [4]])
```

*A los datos que usamos para tratar de estimar las calificaciones los llamaremos features, y a la nota en sí la label del problema. Cada fila es el registro de un alumno, por lo que entendemos que la información de los estudiantes la podemos representar en un espacio 4-dimensional.*

*Bajo estas circunstancias, el algoritmo sigue estos pasos:*

1.  *Para un cierto estudiante sin calificación, calculamos la distancia (en el mencionado espacio 4-dimensional) del estudiante sin calificar a cada uno de los calificados.*

2.  *Habiendo prefijado el parámetro k, escogemos las notas de los k estudiantes más cercanos.*

3.  *Hacemos la media (moda en caso discreto) de estos datos, y esa será la estimación que tengamos del alumno.*


In [ ]:
#Creamos función que, dados dos arrays 1D, nos devuelva la distancia euclídea de los mismos
def euclidean_distance(vec1, vec2):
  #Algunas comprobaciones para mejorar la búsqueda de errores en código son:
  #if (type(vec1)!=np.ndarray) | (type(vec2)!=np.ndarray):
  # raise ValueError('El formato de alguno de los vectores de entrada no es np.array.')
  #if vec1.shape!=vec2.shape:
  # raise ValueError('Los arrays de entrada no tienen la misma forma.')
  return np.sqrt(np.sum((vec1-vec2)**2, axis = -1))

In [ ]:
#Fijamos número de "vecinos" en los que basar la nota
k = 2

#Obtenemos features
features = np.array([[19,  7, 12,  4],
                     [19,  0,  7,  9],
                     [17, 12, 17,  6],
                     [ 8, 10,  1, 12],
                     [ 9,  6,  0, 15],
                     [11, 18,  1, 14],
                     [16,  8, 12,  1],
                     [ 2, 13,  6, 17],
                     [ 0,  7, 13,  8],
                     [15,  9, 10, 15]])

#Obtenemos label
label = np.array([[6],[4],[7],[4],[3],[9],[9],[5],[3],[4]])

#Fijamos un alumno nuevo
new_student = np.array([15, 6, 5, 2])

#Calculamos distancias
distances = np.zeros(label.shape) #Inicializamos un array para contener las distancias
for i in np.arange(label.shape[0]):
  distances[i] = euclidean_distance(features[i,:], new_student)

#Obtenemos los índices de los k vecinos más próximos
optimal_idx = np.argpartition(distances.reshape(-1), k)[:k]

#Mostramos resultado
label_new_student = np.round(np.mean(label[optimal_idx]),2)
print('La predicción para el nuevo estudiante es: {}'.format(label_new_student))

La predicción para el nuevo estudiante es: 7.5
