#Colección de ejercicios de Numpy

##1 - Importa el paquete con el nombre "np".

`pista: import … as …`

In [ ]:
import numpy as np

##2 - Imprime la versión instalada.

`pista: np.__version__, np.show_config`

In [ ]:
print(np.__version__)
np.show_config()

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

##3 - Crea un vector de nulos de tamaño 10.

`pista: np.zeros`

In [ ]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


##4 - Encontrar el tamaño en memoria de un array.

`pista: size, itemsize`

In [ ]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


##5 - Cree un vector nulo de tamaño 10 pero el quinto valor tiene de valor 1.

`pista: array[...]`

In [ ]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


##6 - Cree un vector con valores que van de 10 a 49.

`pista: arange`


In [ ]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


##7 - Invierta un vector (el primer elemento se convierte en el último).

`pista: array[::-1]`

In [ ]:
Z = np.arange(10)
Z = Z[::-1]
print(Z)

[9 8 7 6 5 4 3 2 1 0]


##8 - Cree una matriz de 3x3 con valores que van de 0 a 8.

`pista: reshape`

In [ ]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


##9 - Encuentre los índices de elementos distintos de cero de `[7,5,0,0,2,1]`.

`pista: np.nonzero`

In [ ]:
nz = np.nonzero([7,5,0,0,2,1])
print(nz)

(array([0, 1, 4, 5]),)


##10 - Crear una matriz de identidad de 3x3.

`pista: np.eye`


In [ ]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##11 - Crear una matriz de 3x3x3 con valores aleatorios.

`pista: np.random.random`


In [ ]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.29756913 0.06154764 0.5364401 ]
  [0.3729539  0.08512123 0.00152026]
  [0.07654081 0.12681742 0.1414429 ]]

 [[0.14575687 0.64751916 0.06462168]
  [0.92545469 0.23647161 0.96882828]
  [0.92507284 0.75246267 0.32089517]]

 [[0.09390296 0.73183527 0.74038446]
  [0.42874082 0.70389744 0.78172068]
  [0.13354298 0.5080116  0.37856069]]]


##12 - Cree una matriz de 10x10 con valores aleatorios y encuentre el mínimo y el máximo.

`pista: min, max`

In [ ]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0034959856900877995 0.9997015692774968


##13 - Cree un vector aleatorio de tamaño 50 y encuentre el valor medio.

`pista: mean`

In [ ]:
Z = np.random.random(50)
m = Z.mean()
print(m)

0.47461042880625665


##14 - Cree una matriz de 6x6 con valores 1,2,3,4,5 justo debajo de la diagonal.

`pista: np.diag`

In [ ]:
Z = np.diag(1+np.arange(5),k=-1)
print(Z)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


##15 - Considere una matriz de formas (4,5,6), ¿cuál es el índice (x,y,z) del elemento número 57?

`pista: np.unravel_index`

In [ ]:
print(np.unravel_index(56,(4,5,6)))

(1, 4, 2)


##16 - Normalice una matriz aleatoria de 10x10.

`pista: (x - mean) / std`

In [ ]:
Z = np.random.random((10,10))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.35666488 -1.60902325  0.6473888   0.09347389  0.33847712  0.50637354
   0.19081222 -1.25658825 -0.96381449 -1.32083615]
 [-1.61661804  1.21181049  0.24784032  1.36826753 -1.05456338  1.50357254
  -1.67980054 -0.61245475  0.01584742 -1.6058291 ]
 [-0.30656119  1.2575143   0.5078204   1.0373658  -0.50200432  0.38640687
   0.55763745  1.08351358  0.00602542  0.87119882]
 [ 1.49959016 -1.59746356  1.19931601  0.31002619 -1.61180081  0.16252154
  -1.6635165  -0.80043638 -0.87216791  1.2392847 ]
 [ 1.25044989  0.25357308 -0.22265283  0.54592723  1.22331105  0.0506015
   0.95820456  1.44878891 -1.36772222 -0.78066942]
 [-0.55983705  0.95574446  0.76645839 -0.83367554  0.14440682 -1.02178109
  -0.08475287 -0.33847153 -0.4631279  -1.35352888]
 [ 0.40202483  0.57602327 -0.67996302  1.44903906  1.26951308 -1.10266286
  -0.46695596  1.22041666 -1.62888351 -1.08217654]
 [-0.54533068  0.92446565  1.27707695  0.95398773  0.24438246 -0.43418949
  -1.70149715 -0.47128961  0.93823536 -0.83887769]
 

##17 - Multiplique una matriz de 3x2 por una matriz de 2x5.

In [ ]:
Z = np.dot(np.ones((3,2)), np.ones((2,5)))
print(Z)

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


##18 - ¿Cómo encuentra valores comunes entre dos matrices?

`pista: np.intersect1d`


In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 1 2 9]


##19 - ¿Cómo obtener las fechas de ayer, hoy y mañana?

`pista: np.datetime64, np.timedelta64`


In [ ]:
ayer    = np.datetime64('today') - np.timedelta64(1)
hoy     = np.datetime64('today')
mañana  = np.datetime64('today') + np.timedelta64(1)

##20 - ¿Cómo obtener todas las fechas correspondientes al mes de septiembre de 2020?

`pista: np.arange(dtype=datetime64['D'])`

In [ ]:
Z = np.arange('2020-09', '2020-10', dtype='datetime64[D]')
print(Z)

['2020-09-01' '2020-09-02' '2020-09-03' '2020-09-04' '2020-09-05'
 '2020-09-06' '2020-09-07' '2020-09-08' '2020-09-09' '2020-09-10'
 '2020-09-11' '2020-09-12' '2020-09-13' '2020-09-14' '2020-09-15'
 '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19' '2020-09-20'
 '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24' '2020-09-25'
 '2020-09-26' '2020-09-27' '2020-09-28' '2020-09-29' '2020-09-30']


##21 - Extraiga la parte entera de una matriz aleatoria de números positivos usando 4 métodos diferentes.

`pista: %, np.floor, astype, np.trunc`

In [ ]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[1. 3. 7. 2. 8. 0. 2. 5. 0. 6.]
[1. 3. 7. 2. 8. 0. 2. 5. 0. 6.]
[1. 3. 7. 2. 8. 0. 2. 5. 0. 6.]
[1 3 7 2 8 0 2 5 0 6]
[1. 3. 7. 2. 8. 0. 2. 5. 0. 6.]


##22 - Cree una matriz de 10x10 con valores de fila que van de 0 a 9.

`pista: np.arange`

In [ ]:
Z = np.zeros((10,10))
Z += np.arange(10)
print(Z)


[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]


##23 - Cree un vector de tamaño 5 con valores que van de 0 a 1, ambos excluidos.

`pista: np.linspace`

In [ ]:
Z = np.linspace(0,1,6,endpoint=False)[1:]
print(Z)

[0.16666667 0.33333333 0.5        0.66666667 0.83333333]


##24 - Cree un vector aleatorio de tamaño 25 y ordénelo.

`pista: sort`

In [ ]:
Z = np.random.random(25)
Z.sort()
print(Z)

[0.01673529 0.11798242 0.17731148 0.39698763 0.43501964 0.44391221
 0.46033752 0.47803456 0.5387924  0.56898292 0.61025126 0.63758637
 0.63974624 0.64694219 0.65433458 0.73938135 0.79061932 0.79811698
 0.80602027 0.82105876 0.84522792 0.89489748 0.92491087 0.95524995
 0.97355769]


##25 - Sume un vector usando `np.add.reduce`.

In [ ]:
Z = np.arange(10)
np.add.reduce(Z)

45

##26 - Considere dos matrices aleatorias A y B, verifique si son iguales.

`pista: np.allclose, np.array_equal`

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Si son identicas en forma pero no tienen los mismos valores (hay tolerancia).
equal = np.allclose(A,B)
print(equal)

# Si son identicas en forma y además tienen los mismos valores (no hay tolerancia).
equal = np.array_equal(A,B)
print(equal)

##27 - Cree un vector aleatorio de tamaño 25 y reemplace el valor máximo por 0.

`pista: argmax`


In [ ]:
Z = np.random.random(25)
Z[Z.argmax()] = 0
print(Z)

[0.01791447 0.89274845 0.07780698 0.59020409 0.34921659 0.48297902
 0.10589555 0.44398151 0.75114015 0.95186396 0.07414586 0.28576626
 0.56284085 0.56096044 0.56298931 0.32226905 0.77730745 0.33032758
 0.77637948 0.05671296 0.08633789 0.90503662 0.14791726 0.
 0.40295987]


##28 - ¿Cómo imprimir todos los valores de una matriz?

`pista: np.set_printoptions`

In [ ]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


##29 - ¿Cómo encontrar el valor más cercano, a un escalar dado, en un vector?

`pista: argmin`


In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

##30 - ¿Cómo convertir una matriz `float` (32 bits) en tipo `int` (32 bits)?

`pista: view and [:] =`

In [ ]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[34 36 30 55 98 66 29 70 58 93]


##31 - ¿Cuál es el equivalente de `enumerate` para matrices en `numpy`?

`pista: np.ndenumerate, np.ndindex`

In [ ]:
Z = np.arange(16).reshape(4,4)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11
(3, 0) 12
(3, 1) 13
(3, 2) 14
(3, 3) 15
(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11
(3, 0) 12
(3, 1) 13
(3, 2) 14
(3, 3) 15


##32 - Restar la media de cada fila a una matriz.

`pista: mean(axis=, keepdims=)`


In [ ]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)

##33 - ¿Cómo ordenar una matriz por la enésima columna?

`pista: argsort`

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print("===========")
print(Z[Z[:,1].argsort()])

[[4 5 7]
 [1 2 9]
 [5 7 3]]
[[1 2 9]
 [4 5 7]
 [5 7 3]]


##34 - ¿Cómo saber si una matriz 2D tiene columnas nulas?

`pista: any, ~`


In [ ]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


##35 - Encuentre el valor más cercano de un valor dado en una matriz.

`pista: np.abs, argmin, flat`


In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4855050975491537
